name: sound_vault
description: SoundVault — A local music player with real FFT visualizer.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  file_picker: ^10.3.10
  flutter_soloud: ^4.1.7
  audio_service: ^0.18.15
  permission_handler: ^11.4.0
  path_provider: ^2.1.4
  path: ^1.9.0
  audiotags: 1.4.5
  http: ^1.2.1
  just_audio: ^0.10.6
  just_audio_windows: ^0.2.2
  audio_session: ^0.1.25
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0A0A0A"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/icon/icon.png"
