name: sound_vault
description: SoundVault — A local music player with real FFT visualizer.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  file_picker: ^10.3.10
  flutter_soloud: ^4.1.7
  audio_service: ^0.18.15
  permission_handler: ^13.0.2
  path_provider: ^2.1.4
  path: ^1.9.0
  audiotags: 1.4.5
  http: ^1.2.1
  just_audio: ^0.10.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
